#ifndef CMD_H
#define CMD_H

#define SERVER_MESSAGE 0x00
#define GET_SESSION_ID 0x01
#define TRADE_DH_PARAMS 0x02
#define TRADE_KEY 0x03



#define LOGIN 0x04
#define LOGIN_SUCCESS 0x05
#define REGISTER 0x06
#define LOGOUT 0x07

#define GET_ONLINE_USERS 0x08

#define GET_JOINED_GROUPS 0x09

#define CREATE_GROUP 0x0A
#define CREATE_GROUP_SUCCESS 0x0B

#define JOIN_GROUP 0x0C
#define JOIN_GROUP_SUCCESS 0x0D

#define LEAVE_GROUP 0x0E
#define LEAVE_GROUP_SUCCESS 0x0F

#define DELETE_GROUP 0x10
#define DELETE_GROUP_SUCCESS 0x11

#define SEND_MESSAGE 0x12
#define RECEIVE_MESSAGE 0x13

#define SEND_GROUP_MESSAGE 0x12
#define RECEIVE_GROUP_MESSAGE 0x13

#define JOIN_GROUP_FAILED 0x14
#define DELETE_GROUP_FAILED 0x15
#define LEAVE_GROUP_FAILED 0x16
#define CREATE_GROUP_FAILED 0x17


#endif
